name: integracion_continua

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Establecer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ingreso a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Compilar y publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: acruxsource/ci:v1.0
